function A = A_Matrix(L1,L1c,L2,delta0,psi20,gamma0,u1)
%A_Matrix
%    A = A_Matrix(L1,L1c,L2,DELTA0,PSI20,GAMMA0,U1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    19-Mar-2026 23:03:05

t2 = cos(gamma0);
t3 = cos(psi20);
t4 = tan(delta0);
t5 = sin(gamma0);
t6 = sin(psi20);
t9 = 1.0./L1;
t10 = 1.0./L2;
t7 = L1.*t2;
t8 = L1.*t5;
t11 = L1c.*t2.*t4;
t12 = L1c.*t4.*t5;
t13 = -t12;
t14 = t8+t11;
t15 = t7+t13;
t16 = t9.*t10.*t15.*u1;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t6.*t9.*t15.*u1,t3.*t9.*t15.*u1,0.0,0.0,-t3.*t9.*t14.*u1,-t6.*t9.*t14.*u1,t16,-t16],[4,4]);
end
