function B = B_Matrix(L1,L1c,L2,delta0,psi20,gamma0,u1)
%B_Matrix
%    B = B_Matrix(L1,L1c,L2,DELTA0,PSI20,GAMMA0,U1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    19-Mar-2026 23:03:05

t2 = cos(delta0);
t3 = cos(gamma0);
t4 = sin(gamma0);
t5 = 1.0./L1;
t6 = 1.0./L2;
t7 = 1.0./t2.^2;
B = [-L1c.*t4.*t5.*t7.*u1.*cos(psi20);(L1c.*t4.*t5.*u1.*sin(psi20))./(sin(delta0).^2-1.0);L1c.*t3.*t5.*t6.*t7.*u1;t5.*t6.*t7.*u1.*(L2-L1c.*t3)];
end
