function f_trailer = f_tractor_trailer(X2,Y2,psi2,gamma,delta,u1,L1,L1c,L2)
%F_TRACTOR_TRAILER
%    F_TRAILER = F_TRACTOR_TRAILER(X2,Y2,PSI2,GAMMA,DELTA,U1,L1,L1c,L2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    19-Mar-2026 23:03:05

t2 = cos(gamma);
t3 = tan(delta);
t4 = sin(gamma);
t6 = 1.0./L1;
t7 = 1.0./L2;
t5 = L1.*t2;
t8 = L1c.*t3.*t4;
t9 = t4.*t7.*u1;
t12 = L1c.*t2.*t3.*t6.*t7.*u1;
t10 = -t8;
t11 = t5+t10;
f_trailer = [t6.*t11.*u1.*cos(psi2);t6.*t11.*u1.*sin(psi2);t9+t12;-t9-t12+t3.*t6.*u1];
end
