function W = W_Matrix(L1,L1c,L2,delta0,psi20,gamma0,u1)
%W_Matrix
%    W = W_Matrix(L1,L1c,L2,DELTA0,PSI20,GAMMA0,U1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    19-Mar-2026 23:03:05

t2 = cos(delta0);
t3 = cos(gamma0);
t4 = cos(psi20);
t5 = sin(delta0);
t6 = tan(delta0);
t7 = sin(gamma0);
t8 = sin(psi20);
t12 = 1.0./L1;
t13 = 1.0./L2;
t9 = t2.^2;
t10 = L1.*t3;
t11 = L1.*t7;
t15 = L1c.*delta0.*t3;
t16 = L1c.*t3.*t6;
t17 = L1c.*t6.*t7;
t19 = L1c.*t2.*t3.*t5;
t23 = L1c.*gamma0.*t2.*t5.*t7;
t14 = 1.0./t9;
t18 = -t15;
t20 = -t17;
t21 = t9.*t11;
t22 = gamma0.*t9.*t10;
t25 = t11+t16;
t24 = -t22;
t26 = t10+t20;
W = [t4.*t12.*t26.*u1+gamma0.*t4.*t12.*t25.*u1+psi20.*t8.*t12.*t26.*u1+L1c.*delta0.*t4.*t7.*t12.*t14.*u1;t8.*t12.*t26.*u1+gamma0.*t8.*t12.*t25.*u1-psi20.*t4.*t12.*t26.*u1-(L1c.*delta0.*t7.*t8.*t12.*u1)./(t5.^2-1.0);t12.*t13.*t14.*u1.*(t18+t19+t21+t23+t24);-t12.*t13.*t14.*u1.*(t18+t19+t21+t23+t24+L2.*delta0-L2.*t2.*t5)];
end
